pages:
    stage: deploy
    
    script:
    - mkdir .public
    - cp -a examples* .public
    - cp -a *.js .public
    - mv .public public

    artifacts:
        paths:
        - public
    
    only:
    - master
